version: '3.7'

services:
    db:
        container_name: database
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/new/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"

volumes:
    postgres_data: